- draft-turner-lamps-nist-pqc-kem-certificates.md
Fixed small nit, updated and added references.
> Updated references

- draft-turner-lamps-nist-pqc-kem-certificates.md
> Added author name

- draft-turner-lamps-nist-pqc-kem-certificates.md
Added small Sec Considerations
> Updated Sec Considerations

- draft-ietf-lamps-kyber-certificates.md
Switching to 2015/2021 syntax.
Picking Kyber-512 as the example key.
> Updating SPKI ASN.1

- draft-ietf-lamps-kyber-certificates.md
Now uses 2015/2021 ASN.1.
Picked Kyber-512 for the example.
> Updating Private Key Section

- draft-ietf-lamps-kyber-certificates.md
Added Kyber-* PK ASN.1.
Also deleted the Key Usage section because it's not clear we needed it - since it's algorithm and all the strengths use the same value.
> Adding PK ASN.1

- draft-ietf-lamps-kyber-certificates.md
Making the aside blocks consistent
> md: aside consistency

- draft-ietf-lamps-kyber-certificates.md
Minor tweaks to md for ITU references.
> tweaks to ITU-T references

- draft-ietf-lamps-kyber-certificates.md
Swap DRAFT for final FIPS PUB. Also reword intro para.
> Refer to FIPS 203

- draft-ietf-lamps-kyber-certificates.md
Sean's suggestion in the PR never got picked and the build fails now.
> Fix FIPS reference

- example/go.mod
- example/go.sum
- example/main.go
Still need to set the right OIDs, and use seed as private key.
```
bas@localhost ~/scm/kyber-certificates/example $ go run main.go                          
-----BEGIN ML-KEM-768 PRIVATE KEY-----
MIIJdwIBADAOBgwrBgEEAYLaSy2JUgEEgglgeaqdgQWJuOgLwHmb8euLhmprXIu/
mYgb4AJeuYkC0oK0MrtRdLxOVmts+NvKGMqaWJTFiTMfsTYWJZd9H5IQ6Nthj9HB
KpmdPtKQcnB2HYqIJixpbpxrCLeVDZFx4kCfzroM4OVHdlMqN1DGEmco+jZN8hGP
ZJe5pqaGlLmc5HFZNaV+AuwhA9xk76DK6Ya23HigH7cSxUm3lcFFQOOmXvtvd1Zo
NdzMuJRJygsZKQnMl/wzyZXK12lM24Ge2Aev4ysYLVxF2gscJrc6uqO6hwy3O6qo
axAnqdlz3xWw1syn4bxAywF8Vxxwnoytici1LbEK/BZO+kUCloZ0bokTsTqyNORS
kwNYDwZT+AUU+TiVHhuWS3acE6sBNzqtQdi6DfNYmxM4veluc+GHtCUxC0jJpulI
kWcD8RaXjvlpiwkTB9mnyAUs1kh9gnIFJLC47lqJJNYw/rpSzXnA85c63BC0DyRp
W1cBimasrjN4K7I0SvyHfoyBuFmNGDVQPoqEpYwTQzaztwg0B3VgU0dEVqQ90LXD …
```
> Update example to generate ML-KEM keys

- draft-ietf-lamps-kyber-certificates.md
> Update subjectPublicKey description

- draft-ietf-lamps-kyber-certificates.md
Based on what's in draft-ietf-lamps-x509-slhdsa, we can drop some text.
> Tweaks and Streamlines

- draft-ietf-lamps-kyber-certificates.md
Adding ASN.1 pretty print for examples.
> Add ASN.1 pretty print for examples

- draft-ietf-lamps-kyber-certificates.md
> Qualify ML-KEM seed as 'the' private key format, wrap

- draft-ietf-lamps-kyber-certificates.md
> Add Security Considerations.

- draft-ietf-lamps-kyber-certificates.md
> fix the OID in the decoded ML-KEM-1204 private key

- draft-ietf-lamps-kyber-certificates.md
> Drop PKCS#8 example with attribute & public key

- draft-ietf-lamps-kyber-certificates.md
> Drop ToDo In Appendix B

- draft-ietf-lamps-kyber-certificates.md
Remove notes about BIT STRING padding and add notes for RFC editor.
> App C fixes

- draft-ietf-lamps-kyber-certificates.md
Same text from this [PR](https://github.com/lamps-wg/dilithium-certificates/pull/88/files) in the ML-DSA repo.
> Private Key Consistency Testing

- draft-ietf-lamps-kyber-certificates.md
Text to go along with the ASN.1 and Examples.
Also, moved some stuff around.
> Private Key Text

- draft-ietf-lamps-kyber-certificates.md
As noted in this [Issue](https://github.com/lamps-wg/dilithium-certificates/issues/93).
> Aligning with ML-DSA I-D

- draft-ietf-lamps-kyber-certificates.md
just making it consistent across the draft.
> Add quotes for fields

- draft-ietf-lamps-kyber-certificates.md
> Add text to appease

- draft-ietf-lamps-kyber-certificates.md
From Dennis; see #107.
@dennisjackson @vdukhovni PTAL.
> More Implementation Guidance

- draft-ietf-lamps-kyber-certificates.md
Sometimes expanded key sometimes expanded private key. Went with the later.
> Be consistent: expanded private key

- draft-ietf-lamps-kyber-certificates.md
> Add ASN.1 Notes

- draft-ietf-lamps-kyber-certificates.md
Need to explain that the textual and pretty-print are the same.
> More explanation for examples

- draft-ietf-lamps-kyber-certificates.md
Tag for `seed` is not UNIVERSAL.
> Fix Tag description
